### ISSUE TITLE
Additional field always present

### ISSUE THREAD

**Issue by luixal** [VeliovGroup/Meteor-logger-mongo#12]
Hi,

When I log something without adding additional data. This is, something like this:

``` javascript
logger.info('Server started');
```

the additional field is always added (containing a proto, no data). This supposes a problem when I try to check if a log contains extra data using something like:

``` javascript
var log = Logs.findOne();
if (log.additional) {
  console.log('has extra data');
} else {
  console.log('no extra data here!');
}
```

Any ideas?

Thanks!

**Comment by luixal** [comment]
In case someone is facing the same problem, the workaround I'm using at the moment is counting the number of properties of the `additional` object like this:

``` javascript
if (Object.keys(log.additional).length > 0) {
  console.log('has extra data');
} else {
  console.log('no extra data here!');
}
```

:)

**Comment by dr-dimitru** [comment]
Another approach using `underscore` is:

``` js
if (!_.isEmpty(log.additional)) {
  console.log('has extra data');
} else {
  console.log('no extra data here!');
}
```

**Comment by dr-dimitru** [comment]
Hi @luixal , any new on your end?

From v1.1.3 you can use `options.format` property to filter/create records in your own way

**Comment by luixal** [comment]
Hi,

Just a few try-out but... good work! It looks good :)

¿Could you make something similar for logger-console where the string returned by the `format` function is the string shown up in the console? That was my original problem... xD

In case you need inspiration for your spare time, I'm adding to the `additional` object a property called `origin`which takes values `['client',` 'server', 'method','job']` so I have more info about where was the log generated.

**Comment by dr-dimitru** [comment]
> ¿Could you make something similar for logger-console where the string returned by the format function is the string shown up in the console? That was my original problem... xD

It's coming... like today or tomorrow...

> In case you need inspiration for your spare time, I'm adding to the additional object a property called originwhich takes values ['client',` 'server', 'method','job'] so I have more info about where was the log generated.

Good idea, create a ticket on https://github.com/VeliovGroup/Meteor-logger package, I'll implement it later

**Comment by luixal** [comment]
Great, thanks! :)

I'll think about the ticket tomorrow. Maybe it's too much particular. I mean, I guess there's a way for meteor-logger to know if it's logging something from client or server, but seems much difficult to know if it's coming from a simple server function or a method (for not to talk about jobs, hooks, ... that are third party modules).

**Comment by dr-dimitru** [comment]
I guess it's solved?

**Comment by dr-dimitru** [comment]
@luixal ?

**Comment by luixal** [comment]
Sorry for the delay, **totally solved** :)

Thanks!

**Comment by dr-dimitru** [comment]
@luixal thank you!
Do not forget to star this package on [GitHub](https://github.com/VeliovGroup/Meteor-logger-mongo) and [Atmosphere](https://atmospherejs.com/ostrio/loggermongo)
