### ISSUE TITLE
Mongo is not defined on client

### ISSUE THREAD

**Issue by bryanterrell** [VeliovGroup/Meteor-logger-mongo#14]
I'm not sure why this was working some of the time, but now I am only able to get this package working if I change the **package.js** file to use mongo on both client and server, otherwise I get a _Mongo is not defined_ error.

Here's the change I made to get it working:
https://github.com/37d/Meteor-logger-mongo/commit/96887b918cdfbf2677a7ea5dd0f2dcc219c18fb7

I'm invoking it like this:
```
(new LoggerMongo(logger, { collectionName: 'logs' } )).enable({
  enable: true,
  filter: [ 'warn', 'error', 'fatal' ],
  client: false,
  server: true,
});
```

And I'm referencing this package from within another package, which may be why this issue is showing up for me.

**Comment by dr-dimitru** [comment]
Hi @bryanterrell ,

Sorry for delayed response, is that appeared after meteor update? To which version?

**Comment by bryanterrell** [comment]
Hi @dr-dimitru,

No worries. I'm on version 1.4.2.3 of Meteor. I haven't tried other versions recently so not sure if it's due to an update or not. My guess is Meteor started requiring `'mongo'` to be explicitly listed in the `package.js` at some point.

**Comment by dr-dimitru** [comment]
is `meteor add mongo` helps, or only editing package config?

**Comment by bryanterrell** [comment]
I believe I tried that and it wasn't enough. I'd have to try again, though, to confirm.

**Comment by dr-dimitru** [comment]
Hello @bryanterrell ,

I know it's been a while, hope you're still using this package.
I just released [an update](https://github.com/VeliovGroup/Meteor-logger-mongo/releases/tag/2.0.0), should fix this issue.

Let me know, thanks.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
