### ISSUE TITLE
 Error: [LoggerMongo]: `collectionName` or `collection` must be presented [400]

### ISSUE THREAD

**Issue by Gobliins** [VeliovGroup/Meteor-logger-mongo#17]
On running this code:

Meteor.startup(){
  // Initialize Logger:
  const log = new Logger();
  // Initialize and enable LoggerMongo with default settings:
  (new LoggerMongo(log)).enable(); //throws
...
exception is thrown:
W20170718-11:12:33.947(2)? (STDERR) Error: [LoggerMongo]: `collectionName` or `collection` must be presented [400]
W20170718-11:12:33.947(2)? (STDERR)     at new LoggerMongo (packages/ostrio_loggermongo.js:52:13)
W20170718-11:12:33.948(2)? (STDERR)     at initOstrioLogger (imports/api/logger/logger.js:37:4)
W20170718-11:12:33.948(2)? (STDERR)     at  (new LoggerMongo(log)).enable();

**Comment by Gobliins** [comment]
ok wenn initiating the `const AppLogs = new Mongo.Collection('AppLogs');` like in example 2 then the error is not thrown

**Comment by dr-dimitru** [comment]
Hello @Gobliins ,

According to your second message, I'm assuming it's fixed.
Feel free to reopen it in case if the issue still persists on your end.

**Comment by Gobliins** [comment]
Well kinda, but shouldn't there be a default collection if you don't pass it manually?

**Comment by dr-dimitru** [comment]
@Gobliins you need to pass either `collectionName` or `collection`, passing `collectionName` no need to create a collection.
