### ISSUE TITLE
Set custom indexes on collection: [Server] should not include level

### ISSUE THREAD

**Issue by chafey** [VeliovGroup/Meteor-logger-mongo#19]
level is not highly selectable so an index really isn't helpful.  I recommend removing it from the example to avoid wasting unnecessary CPU and disk space

**Comment by dr-dimitru** [comment]
Hello @chafey ,

It's clearly says:

> Set __custom__ indexes on collection

So, it means - use it only if you need it.

I'm agree on making this more obvious, marked as [documentation].
*Text suggestions are welcome.*

**Comment by chafey** [comment]
OK - but putting an index on level is a really bad idea because it is not highly selectable.  Less experienced developers might just cut and paste and note realize the implications - would be better to remove it IMO

**Comment by dr-dimitru** [comment]
@chafey feel free to drop your version of *precaution text* here.
