### ISSUE TITLE
Why store both timestamp and date?

### ISSUE THREAD

**Issue by chafey** [VeliovGroup/Meteor-logger-mongo#21]
This seems redundant - why not just store the date property?

**Comment by dr-dimitru** [comment]
Hello @chafey ,

So you may use one, another or both.

**Comment by chafey** [comment]
Isn't it the exact same data just in two different forms?  If so - what is the justification for storing it twice?  I can't think of anything I can do with the timestamp I can't do with the date.  Seems wasteful and unnecessary, especially for something that could end up holding a lot of data

**Comment by dr-dimitru** [comment]
In case if you will need to build an index, to sort/select records by date, you want to use `timestamp` as it will be almost twice smaller in terms of memory consumption. But in some cases when you need to work with actual *Date*, involving timezones and other *Date* features, you will end up building index on `date` field.

As I've said before - so you may use one, another or both, *to meet everyone's needs*.

Speaking of extra bytes on your storage, in terms of 2017, additional 8 bytes per record is negligible
