### ISSUE TITLE
Extend the schema for log message?

### ISSUE THREAD

**Issue by meecect** [VeliovGroup/Meteor-logger-mongo#25]
### I have a suggestion:

I often find my self logging messages within some subsystem or module or section of code and think it would be useful to have another field that specifies that message type.  That way it becomes very easy to sort all the messages by some category, tag, type, or module name, or whatever we would call that field.

Is it possible to extend the schema that is logged to include an additional column?  Then it would be invoked like:

log.error(message, type, data, userId);

**Comment by meecect** [comment]
...I know, I could make data = {type: 'system'} or whatever, but I thought a separate optional field might be useful, in the same way that there is both a timestamp and date field to suit generic implementations and preferences.

**Comment by dr-dimitru** [comment]
Hello @meecect,

You can extend `additional` object passed to the MongoDB record when calling `log.error`, like:

```js
log.error(message, {
  searchKey: 'value' // <-- will be available in `additional.searchKey` object of MongoDB record
})
```

Let me know if that help in any way

P.S. I'm sorry for the late response

**Comment by dr-dimitru** [comment]
@meecect The MongoDB record can get changed/altered via `{ format: Function }` option passed into `LoggerMongo` constructor, see it in the [initialization docs](https://github.com/veliovgroup/Meteor-logger-mongo#initialization-isomorphic)

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
