### ISSUE TITLE
Use it's own namespace

### ISSUE THREAD

**Issue by zimme** [VeliovGroup/Meteor-logger-mongo#8]
This should really be using it's own namespace. e.g.

``` js
Log.rule('Mongo', {
  enable: true,
});
Log.error(message, data, userId);
```

What if Meteor in the future add `Meteor.log` them self, then this package will be in conflict

**Comment by dr-dimitru** [comment]
Done in [v1.1.0](https://github.com/VeliovGroup/Meteor-logger-mongo/releases/tag/1.1.0)
Thank you @zimme
